Bank/urls.py
from django.contrib import admin
from django.urls import path, include
from django.urls import re_path
from banks import views
import user
from .views import redirect_blog
urlpatterns = [
    path('', redirect_blog),
    #path('/login', user.views.login_page, name='login_url'),
    path('admin/', admin.site.urls),
    path('api/v1/bank/', include('banks.urls')),
    path('api/v1/user/', include('user.urls')),
    path('blog/<int:id_transaction>/', views.transaction_detail, name='tran_detail'),
    path('blog/<int:id>', views.id_transactions, name='id_transaction'),
    path('blog', views.transactions, name='our_blog'),
    path('alert', views.alert_list, name='alert_list'),
    path('export', views.export, name='export_url'),
    path('export2', views.export2, name='export2_url'),
    path('users/<str:username>/', user.views.UserDetailMixin.as_view(), name='user_detail'),
    path('users/<str:username>/update', user.views.UserUpdateMixin.as_view(), name='user_update'),
    path('users/<str:username>/gr_update', user.views.UserProfileUpdateMixin.as_view(), name='user_update_group'),
    path('users/<str:username>/delete', user.views.UserDeleteMixin.as_view(), name='user_delete'),
    path('user/create', user.views.UserCreateMixin.as_view(), name='user_create'),
    path('users', user.views.user_list, name='user_list'),
    path('rules/<int:t_client>/update', user.views.RulesUpdateMixin.as_view(), name='rule_update'),
    path('rules', user.views.rules_list, name='rules_list'),
    path('login', user.views.login_page, name='login_url'),
    path('logout/', user.views.logoutUser, name="logout"),
    path('mypage/', user.views.page, name="mypage"),
]

banks/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *
urlpatterns = [
    path('transaction/create/', TransactionCreateView.as_view()),
    path('client/create/', ClientCreateView.as_view())
]

banks/models.py
from django.db import models
# Create your models here
from user.models import Rules
from datetime import datetime
from datetime import timedelta
from user.centerbank import *

def proverka(amount, currency, date_pub, type_client, payerin):
    dol = float(rate2.replace(',','.'))
    ero = float(rate.replace(',','.'))
    cnt = 1
    zi = Rules.objects.get(t_client=type_client)
    kin = Transaction.objects.filter(payer__id=payerin.id)
    if (currency=="RUR"):
        summa = amount
        if (zi.amountrur_gr < amount) or (zi.amountrur_le > amount):
            return True
    if (currency=="EUR"):
        summa = int(amount * ero)
        if (zi.amounteur_gr < amount) or (zi.amounteur_le > amount):
            return True
        if (zi.eur == False):
            return True
    if (currency=="USD"):
        summa = int(amount * usd)
        if (zi.amountusd_gr < amount) or (zi.amountrur_le > amount):
            return True
        if (zi.usd == False):
            return True
    for t in kin:
        d1 = datetime.strptime(str(t.date_pub)[:-7:], "%Y-%m-%d %H:%M:%S")
        d2 = datetime.strptime(str(datetime.now())[:-7:], "%Y-%m-%d %H:%M:%S")
        d3 = d2 + timedelta(hours=-zi.date_amount)
        d4 = d2 + timedelta(hours=-zi.date_count)
        if d1 > d3:
            cnt += 1
        elif d1 > d4:
            if (currency=="USD"):
                summa += int(summa * usd)
            elif (currency=="EUR"):
                summa += int(summa * ero)
            else:
                summa += summa
        else:
            break
    if cnt >= zi.count or summa > zi.amountrur_gr:
        return True
    return False

class Client(models.Model):
    client = models.CharField(max_length=150, db_index=True)
    phone_number = models.IntegerField(unique=True)
    email = models.EmailField(max_length=150, default='musa@musa.ru')
    TYPE_CLIENT = (
        (1, "Брокер"),
        (2, "Кредитная карта"),
        (3, "Дебетовая карта"),
        (4, "Юридическое лицо"),
        (5, "Сберегательный счет"),
    )
    t_client = models.IntegerField(choices=TYPE_CLIENT)

    def __str__(self):
        return (str(self.id) + " : " + self.client + " " + self.get_t_client_display())

class Transaction(models.Model):
    payer = models.ForeignKey(Client, on_delete = models.CASCADE)
    id_transaction = models.AutoField(primary_key=True, auto_created=True, unique=True)
    TYPE_TRANS = (
        (1, "Перевод физ. лицу"),
        (2, "Перевод перевод юр. лицу")
    )
    t_trans = models.IntegerField(choices=TYPE_TRANS, verbose_name="Тип транзакции")
    amount = models.IntegerField(db_index=True, verbose_name="Сумма перевода")
    currency = models.CharField(max_length=3, verbose_name="Валюта")
    payer_bank_name = models.CharField(max_length=100, verbose_name="Банк плательщика")
    date_pub = models.DateTimeField(auto_now_add=True, verbose_name="Дата проведения транзакции")
    payee = models.CharField(max_length=150, verbose_name="Получатель")
    payee_bank_name = models.CharField(max_length=150, verbose_name="Банк получателя")
    alert = models.BooleanField(blank=True)

    def save(self, *args, **kwargs):
        if not self.alert:
            self.alert = proverka(self.amount, self.currency, self.date_pub, self.payer.t_client, self.payer)
        super().save(*args, **kwargs)

    class Meta:
        ordering = ['-date_pub']

Bank/views.py
from django.http import HttpResponse
from django.shortcuts import redirect

def redirect_blog(request):
    return redirect('login_url', permanent=True)

banks/views.py
from django.shortcuts import render
from .models import *
from rest_framework import generics
from .serializers import *
from django.core.paginator import Paginator
from user.models import UserProfile
from .filters import *
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
import csv
from django.http import HttpResponse
from user.models import *
from django.db.models import Q
from djpjax import pjax

tira = Transaction.objects.all()
class TransactionCreateView(generics.CreateAPIView):
    serializer_class = TransactionDetailSerializer

class ClientCreateView(generics.CreateAPIView):
    serializer_class = ClientDetailSerializer

@login_required
def transactions(request):
    posts = Transaction.objects.all()
    myFilter = OrderFilter(request.GET, queryset=posts)
    posts = myFilter.qs
    return render(request, 'bank/reg.html', {'posts': posts, 'myFilter': myFilter})

@login_required
def id_transactions(request, id):
    posts = Transaction.objects.filter(payer_id=id)
    tren = posts[0].payer.client
    return render(request, 'bank/client_transactions.html', context={'posts': posts, 'tren': tren})

@login_required
def alert_list(request):
    user = UserProfile.objects.get(user__username=request.user)
    posts = Transaction.objects.filter(Q(alert=True) & Q(payer__t_client__in=user.type_client.all()))
    return render(request, 'bank/alerts_list.html', {'posts': posts})

@login_required
def transaction_detail(request, id_transaction):
    post = Transaction.objects.get(id_transaction=id_transaction)
    return render(request, 'bank/trans_detail.html', {'post': post})

@login_required
def export(request):
    response = HttpResponse(content_type='text/csv')
    writer = csv.writer(response)
    writer.writerow(['ID', 'Тип транзакции', 'сумма', 'валюта', 'банк плательщика', 'дата транзакции', 'Банк получателя', 'Alert'])
    for member in Transaction.objects.all().values_list('id_transaction', 't_trans', 'amount', 'currency', 'payer_bank_name', 'date_pub', 'payee', 'payee_bank_name', 'alert'):
        writer.writerow(member)

    response['Content-Disposition'] = 'attachment; filename="transaction.csv"'

    return response

@login_required
def export2(request):
    response = HttpResponse(content_type='text/csv')
    writer = csv.writer(response)
    user = UserProfile.objects.get(user__username=request.user)
    writer.writerow(['ID', 'Тип транзакции', 'сумма', 'валюта', 'банк плательщика', 'дата транзакции', 'Банк получателя', 'Alert'])
    for member in Transaction.objects.filter(Q(alert=True) & Q(payer__t_client__in=user.type_client.all())).values_list('id_transaction', 't_trans', \
    'amount', 'currency', 'payer_bank_name', 'date_pub', 'payee', 'payee_bank_name', 'alert'):
        writer.writerow(member)

    response['Content-Disposition'] = 'attachment; filename="alert.csv"'

    return response

templates/bank/alerts_list.html
{% extends 'bank/shablon.html'%}

{% block title %}
    Transactions list
{% endblock %}

{% block content %}
    <div class="layer6">
      <a class="btn btn-primary" button type="submit" href="{% url 'export2_url' %}">Export</a>
    </div>
    <h1 class='mb-5'>Alerts:</h1>
      {% for post in posts %}
        {% include 'bank/include/post_card_template.html'%}
    {% endfor %}
{% endblock %}

templates/bank/client_transactions.html
{% extends 'bank/shablon.html'%}

{% block title %}
    Transactions list
{% endblock %}

{% block content %}
   <div class="layer5">
    <h1 class='mb-5'>Transactions of {{ tren }}:</h1>
    {% for post in posts %}
      {% include 'bank/include/post1_card_template.html'%}
    {% endfor %}
   <div>
{% endblock %}

templates/bank/group_update.html
{% extends 'bank/shablon.html'%}

{% block title %}
    group update - {{ block.super }}
{% endblock %}

{% block content %}
    <form class="" action="{% url 'user_update_group' userprofile.user %}" method="post">
      {% csrf_token %}
          <div class="form-group">
              {% if field.errors %}
                  <div class="alert alert-danger">
                      {{ field.errors }}
                  </div>
              {% endif %}
              {{ form.type_client.label }}
              {{ form.type_client}}
          </div>
       <button type="submit" class="btn btn-primary">Изменить</button>
    </form>
{% endblock %}

templates/bank/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Bank</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->
	<link rel="icon" type="image/png" href="{% static 'images/icons/bank.ico' %}"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'fonts/Linearicons-Free-v1.0.0/icon-font.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/animate/animate.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/css-hamburgers/hamburgers.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/animsition/css/animsition.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/select2/select2.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/daterangepicker/daterangepicker.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'css/util.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
<!--===============================================================================================-->
</head>
<body>

	<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100 p-t-50 p-b-90">
				<form class="login100-form validate-form flex-sb flex-w" action="{% url 'login_url' %}" method="post">
					{% csrf_token %}
					<span class="login100-form-title p-b-51">
						Login
					</span>
							<div class="wrap-input100 validate-input m-b-16" data-validate = "Username is required">
								<input class="input100" type="text" name='username' placeholder="Username">
								<span class="focus-input100"></span>
							</div>


							<div class="wrap-input100 validate-input m-b-16" data-validate = "Password is required">
								<input class="input100" type="password" name='password' placeholder="Password">
								<span class="focus-input100"></span>
							</div>


							<div class="container-login100-form-btn m-t-17">
								<button class="login100-form-btn" type="submit">
									Login
								</button>
							</div>
				</form>
			</div>

			{% for message in messages %}
				<p id="messages">{{message}}</p>
			{% endfor %}
		</div>
	</div>


	<div id="dropDownSelect1"></div>

<!--===============================================================================================-->
	<script src="vendor/jquery/jquery-3.2.1.min.js"></script>
<!--===============================================================================================-->
	<script src="vendor/animsition/js/animsition.min.js"></script>
<!--===============================================================================================-->
	<script src="vendor/bootstrap/js/popper.js"></script>
	<script src="vendor/bootstrap/js/bootstrap.min.js"></script>
<!--===============================================================================================-->
	<script src="vendor/select2/select2.min.js"></script>
<!--===============================================================================================-->
	<script src="vendor/daterangepicker/moment.min.js"></script>
	<script src="vendor/daterangepicker/daterangepicker.js"></script>
<!--===============================================================================================-->
	<script src="vendor/countdowntime/countdowntime.js"></script>
<!--===============================================================================================-->
	<script src="js/main.js"></script>

</body>
</html>

templates/bank/reg.html
{% extends 'bank/shablon.html'%}

{% block title %}
    Transactions list
{% endblock %}

{% block content %}
   <div class="layer3">
    <div class="row">
    	<div class="col">
        <div class="card-header">
          <ul class="nav nav-tabs card-header-tabs">
              <li class="nav-item">
                  <a class="nav-link" data-toggle="tab" href="#item1">Транзакция</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link" data-toggle="tab" href="#item2">Alert</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link" data-toggle="tab" href="#item3">Сумма</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link" data-toggle="tab" href="#item4">Дата</a>
              </li>
          </ul>
        </div>
        <form method="get">
          <div class="card-body tab-content">
            <div class="tab-pane fade" id="item1">
                <p> Тип транзакции: {{myFilter.form.t_trans}} </p>
                <p> Банк плательщика: {{myFilter.form.payer_bank_name}} </p>
                <p> Банк получателя: {{myFilter.form.payee_bank_name}} </p>
                <p> Валюта: {{myFilter.form.currency}} </p>
            </div>
            <div class="tab-pane fade" id="item2">
                <p> Alert: {{myFilter.form.alert}} </p>
            </div>
            <div class="tab-pane fade" id="item3">
                <p> Сумма больше или равно: {{myFilter.form.start_amount}} </p>
                <p> Сумма меньше или равно: {{myFilter.form.end_amount}} </p>
            </div>
            <div class="tab-pane fade" id="item4">
                <p> Дата больше или равно: {{myFilter.form.start_date}} </p>
                <p> Дата меньше или равно: {{myFilter.form.end_date}} </p>
            </div>
          </div>
        <button class="btn btn-primary" type="submit">Search</button>
    	</div>
    </div>
   </div>
   <div class="layer4">
     <a class="btn btn-primary" button type="submit" href="{% url 'export_url' %}">Export</a>
   </div>
   <div class="layer5">
    <h1 class='mb-5'>Transactions:</h1>
    {% for post in posts %}
      {% include 'bank/include/post_card_template.html'%}
    {% endfor %}
   <div>
{% endblock %}

templates/bank/rule_update.html
{% extends 'bank/shablon.html'%}

{% block content %}
    <form action="{% url 'rule_update' rule.id %}" method="post">
          {% csrf_token %}
          {% for field in form %}
              <div class="form-group">
                    {% if filed.errors %}
                        <div class="alert alert-danger">
                              {{ field.errors }}
                        </div>
                    {% endif %}
                    {{ field.label }}
                    {{ field }}
              </div>
          {% endfor %}
          <div class="layer1">
            <button type="submit" class="btn btn-primary">Update</button>
          </div>
    </form>
{% endblock %}

templates/bank/rules_list.html
{% extends 'bank/shablon.html'%}

{% block title %}
    Users list
{% endblock %}

{% block content %}
  {% for rule in users.type_client.all %}
      <h1 class='mb-5'>{{ rule.get_t_client_display }}:</h1>
      <table class="table table-bordered">
        <thead>
          <tr>
            <th scope="col">Название правила</th>
            <th scope="col">Значение</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <th scope="row"> Верхний предел суммы в рублях</th>
            <td>{{ rule.amountrur_gr }}</td>
          </tr>
          <tr>
            <th scope="row"> Нижний предел суммы в рублях</th>
            <td>{{ rule.amountrur_le }}</td>
          </tr>
          <tr>
            <th scope="row"> Верхний предел суммы в долларах</th>
            <td>{{ rule.amountusd_gr }}</td>
          </tr>
          <tr>
            <th scope="row"> Нижний предел суммы в долларах</th>
            <td>{{ rule.amountusd_le }}</td>
          </tr>
          <tr>
            <th scope="row"> Верхний предел суммы в евро</th>
            <td>{{ rule.amounteur_gr }}</td>
          </tr>
          <tr>
            <th scope="row"> Нижний предел суммы в евро</th>
            <td>{{ rule.amounteur_le }}</td>
          </tr>
          <tr>
            <th scope="row"> Макс. количество транзакций </th>
            <td>{{ rule.count }}</td>
          </tr>
          <tr>
            <th scope="row"> Время для транзакций(в часах) </th>
            <td>{{ rule.date_amount }}</td>
          </tr>
          <tr>
            <th scope="row"> Время для количества(в часах) </th>
            <td>{{ rule.date_count }}</td>
          </tr>
          <tr>
            <th scope="row"> Транзакции в евро </th>
            {% if rule.eur %}
              <td> Разрешено </td>
            {% else %}
              <td> Запрещено </td>
            {% endif %}
          </tr>
          <tr>
            <th scope="row"> Транзакции в долларах </th>
            {% if rule.usd %}
              <td> Разрешено </td>
            {% else %}
              <td> Запрещено </td>
            {% endif %}
          </tr>
        </tbody>
      </table>
      <div class="layer1">
        <a class="btn btn-primary" button type="button" href="{% url 'rule_update' t_client=rule.t_client %}">Изменить</a>
      </div>
  {% endfor %}
{% endblock %}

templates/bank/search.html
{% extends 'bank/shablon.html' %}

{% block content %}

<h1 class='mb-5'>Transactions:</h1>
{% for post in posts %}
  {% include 'bank/include/post_card_template.html'%}
{% endfor %}
{% endblock %}

templates/bank/shablon.html
{% extends 'bank/base_block.html'%}

{% block admin-panel %}
    <div class="btn-group">
        <a class="btn btn-danger" button type="button" href="{% url 'logout' %}">Выйти</a>
    </div>
{% endblock %}

templates/bank/trans_detail.html
{% extends 'bank/shablon.html'%}
{% block title %}
    Information about transaction
{% endblock %}
{% block content %}
    <h1 class="mt-5">
        ID клиента: {{ post.payer.id }}, Имя: {{ post.payer.client }}
    </h1>
    <p>ID-транзакции: {{ post.id_transaction }}</p>
    <p>Тип транзакции: {{ post.get_t_trans_display }}</p>
    <p>Тип клиента: {{ post.payer.get_t_client_display }}</p>
    <p>Сумма: {{ post.amount }}</p>
    <p>Валюта: {{ post.currency }}</p>
    <p>Банк: {{ post.payer_bank_name }}</p>
    <p>Дата: {{ post.date_pub }}</p>
{% endblock %}

templates/bank/user_create.html
{% extends 'bank/shablon.html'%}

{% block title %}
    Create User - {{ block.super }}
{% endblock %}


{% block content %}
    <form class="" action="{% url 'user_create' %}" method="post">
      {% csrf_token %}
          <div class="form-group">
              {% if field.errors %}
                  <div class="alert alert-danger">
                      {{ field.errors }}
                  </div>
              {% endif %}
              {{ form.username.label }}
              {{ form.username}}

              {{ form.password.label }}
              {{ form.password}}
          </div>
       <button type="submit" class="btn btn-primary">Создать</button>
    </form>
{% endblock %}

templates/bank/user_detail.html
{% extends 'bank/shablon.html'%}

{% block title %}
    User Information
{% endblock %}

{% block content %}
    <h1 class="mt-5">{{ users.username }}</h1>
    <p>ID: {{ users.id }}</p>
    <p>Дата создания пользователя: {{ users.date_joined.date }}</p>
    {% if not users.last_login.date %}
      <p> Дата последнего входа на сайт: Еще не заходил </p>
    {% else %}
      <p> Дата последнего входа на сайт: {{ users.last_login.date }} </p>
    {% endif %}
    <p>Работает с клиентами: </p>
    {% if us %}
      <ol>
        {% for t in us.type_client.all %}
          <li>{{ t }}</li>
        {% endfor %}
      <ol>
    {% endif %}
    <div class="btn-group-vertical">
      <div class="layer2">
        <a class="btn btn-primary" button type="button" href="{% url 'user_update' username=users.username %}">Изменить данные пользователя</a>
      </div>
      <div class="layer2">
        <a class="btn btn-success" button type="button" href="{% url 'user_update_group' username=users.username %}">Изменить/Добавить группу</a>
      </div>
      <div class="layer2">
        <a class="btn btn-danger" button type="button"  href="{% url 'user_delete' username=users.username %}">Удалить пользователя</a>
      </div>
    </div>
{% endblock %}

templates/bank/user_list.html
{% extends 'bank/shablon.html'%}

{% block title %}
    Users list
{% endblock %}

{% block content %}
    <table class="table">
      <thead class="thead-dark">
        <tr>
          <th scope="col">ID</th>
          <th scope="col">Username</th>
          <th scope="col">Дата последнего входа</th>
        </tr>
      </thead>
    {% for us in users %}
        <tbody>
          <tr>
            <th scope="row">{{ us.id }}</th>
            <td><a href="{% url 'user_detail' username=us.username %}">{{ us.username }}</a></td>
            {% if not us.last_login.date %}
              <td> Еще не заходил </td>
            {% else %}
              <td> {{ us.last_login.date }} </td>
            {% endif %}
          </tr>
        </tbody>
    {% endfor %}
    </table>
    <div class="layer2">
      <div class="btn-group">
          <a class="btn btn-info" button type="button" href="{% url 'user_create' %}">Создать пользователя</a>
      </div>
    </div>
{% endblock %}

templates/bank/user_update.html
{% extends 'bank/shablon.html'%}

{% block content %}
    <form action="{% url 'user_update' user.username %}" method="post">
          {% csrf_token %}
          {% for field in form %}
              <div class="form-group">
                    {% if filed.errors %}
                        <div class="alert alert-danger">
                              {{ field.errors }}
                        </div>
                    {% endif %}
                    {{ field.label }}
                    {{ field }}
              </div>
          {% endfor %}
          <button type="submit" class="btn btn-primary">Update</button>
    </form>
{% endblock %}